name: Get Issue Event details
on: 
  issues:
    types: opened
jobs:
  getEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub event details
        run: echo "${{ github.event }}"
